import Head from "next/head";
import { Inter } from "next/font/google";
import { AppBar, Box, Toolbar } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  return (
    <>
      <Head>
        <title>ello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Box className={inter.className} component="main">
        <Box sx={{ bgcolor: "primary.main" }}>test</Box>
      </Box>
    </>
  );
};

export default Home;
